dist: xenial
language: python
cache:
  directories:
    - "$HOME/.ccache"
    - "$HOME/.local"
addons:
  apt:
    packages:
      - gperf
before_install:
  - export PATH="/usr/lib/ccache:$HOME/.local/bin:$PATH"
  - if [[ "$USE_PYPY3" ]]; then deactivate; (cd ~ && wget -q "https://bitbucket.org/pypy/pypy/downloads/$PYPY3_NAME.tar.bz2" -O "$PYPY3_NAME.tar.bz2" && tar -xaf "$PYPY3_NAME.tar.bz2") && export PATH="$HOME/$PYPY3_NAME/bin:$PATH" && (cd "$HOME/$PYPY3_NAME/bin" && ln -s pypy3 python && ln -s pypy3 python3) && hash -r && pypy3 -m ensurepip && pypy3 -m pip install --upgrade pip; fi
install:
  - pip install coverage codecov pyvcd bitarray Jinja2
  - git clone https://github.com/YosysHQ/yosys
  - (cd yosys && if ! yosys -V || [ $(git rev-parse HEAD $(yosys -V | awk 'match($0,/sha1 ([0-9a-f]+)/,m) { print m[1] }') | uniq | wc -l) != 1 ]; then make CONFIG=gcc ENABLE_ABC=0 PREFIX=$HOME/.local install; fi)
  - (git clone https://github.com/YosysHQ/SymbiYosys && cd SymbiYosys && make PREFIX=$HOME/.local install)
  - if ! yices -V; then (git clone https://github.com/SRI-CSL/yices2.git && cd yices2 && autoconf && ./configure --prefix=$HOME/.local && make && make install); fi
script:
  - python --version
  - pip --version
  - python setup.py develop
  - coverage run -m unittest discover
  - codecov
matrix:
  include:
#  - python: 3.6
#  - python: 3.7
  - python: 3.6
    env: USE_PYPY3=1 PYPY3_NAME=pypy3.6-v7.1.1-linux64
